In [66]:
import numpy as np

In [67]:
list_1 = [1,2,3,4,5,6,7,8,9,10]

np.array(list_1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
new_arr_from_list = np.array(list_1)                       #convert list into array
new_arr_from_list * 2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
new_arr_from_list.ndim    # dimensionality of the array 1d or 2d

1

In [70]:
# generate array between range
arr= np.arange(0,10)
arr*2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
# reshaping dimensions  of array
arr_before_reshape = np.arange(1,11)
arr_after_reshape = arr_before_reshape.reshape(5,2)
arr_after_reshape


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [72]:
np.size(arr_after_reshape)        # gives the count of elements inside array

10

In [73]:
np.zeros((4,6),dtype=int)




array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [74]:

np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [75]:
np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [76]:
np.random.random(3)      #1d                      # random numbers between 0 and 1

array([0.42803765, 0.16168439, 0.39942881])

In [77]:
np.random.random((3,3))      #2d

array([[0.34323144, 0.99569796, 0.81755956],
       [0.80159921, 0.32034911, 0.17489977],
       [0.68835582, 0.19162642, 0.43897476]])

In [78]:
np.random.randint(4,size = 10)                      # random values in range of 0 - 4 and size of array is 10       #1d

array([3, 1, 1, 2, 0, 3, 1, 2, 0, 1])

In [79]:
np.random.randint(4,100,size = 10)                      # random values in range of 4 - 100 and size of array is 10

array([14, 22, 85, 89, 35, 13, 99, 31, 14, 82])

In [80]:
np.random.randint(4,100,size = (5,5))                      # random values in range of 4 - 100 and size of array is 10           #2d

array([[87, 52, 64, 90,  9],
       [30, 21, 51, 59, 72],
       [21, 86, 53, 11, 75],
       [37, 65, 19, 89, 62],
       [42, 63, 32, 98, 93]])

In [81]:
add_arr_1 = np.arange(1,10).reshape(3,3)
add_arr_2 = np.arange(11,20).reshape(3,3)

print(add_arr_1)

add_arr_2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [82]:
add_arr_1 * add_arr_2 # normal multiplication

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [83]:
add_arr_1.dot(add_arr_2) # matrix multiplication

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [84]:
min_find_arr = np.random.randint(1,50,size = (8,6))

In [85]:

np.min(min_find_arr)          # find min of whole array

np.min(min_find_arr,axis=0)                         # find min of column wise array

array([ 8,  4,  8,  7, 12,  2])

In [86]:
np.max(min_find_arr,axis=0)

array([47, 44, 48, 40, 46, 45])

In [87]:
np.mean(min_find_arr)

25.291666666666668

In [88]:
np.mean(min_find_arr,axis=0)

array([22.125, 23.75 , 26.75 , 23.25 , 31.75 , 24.125])

In [89]:
np.sort(min_find_arr,axis = 0)                          # 0  column wise sorting 1 row wise sorting

array([[ 8,  4,  8,  7, 12,  2],
       [14,  6, 11, 13, 21, 10],
       [14, 13, 14, 15, 29, 10],
       [16, 21, 24, 20, 30, 24],
       [18, 29, 31, 24, 35, 29],
       [24, 35, 36, 27, 40, 29],
       [36, 38, 42, 40, 41, 44],
       [47, 44, 48, 40, 46, 45]])

In [90]:
# array manipulation

In [91]:
stack_arr_1 = np.arange(1,10).reshape(3,3)
stack_arr_2 = np.arange(11,20).reshape(3,3)


np.vstack((stack_arr_1,stack_arr_2))                      # vertical stack concatenation


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [92]:
np.hstack((stack_arr_1,stack_arr_2))     #  horizontal  stack concatenation

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [93]:
np.concatenate((stack_arr_1,stack_arr_2),axis = 0)                 # vertical stack concatenation

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [94]:
np.concatenate((stack_arr_1,stack_arr_2),axis = 1)                 # horizontal stack concatenation

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [95]:
split_arr = np.arange(1,37).reshape(6,6)
print(split_arr)
np.vsplit(split_arr,3)
# np.hsplit(split_arr,3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [96]:
np.ravel(split_arr)        # makes the data flattened to  1d data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [97]:
np.transpose(split_arr)

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [98]:
"""questions

Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to
use the NumPy package and do some tasks related to that.

Tasks To Be Performed:
1. Create a 3x3 matrix array with values ranging from 2 to 10.

2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]

4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.

5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1

Perform the following tasks:
a. Extract the 1st row from the array
b. Extract the last element from the array
  """

'questions\n\nProblem Statement:\nYou work in XYZ Corporation as a Data Analyst. Your corporation has told you to\nuse the NumPy package and do some tasks related to that.\n\nTasks To Be Performed:\n1. Create a 3x3 matrix array with values ranging from 2 to 10.\n\n2. Create a NumPy array having user input values and convert the integer\ntype to the float type of the elements of the array. For instance: Original\narray [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]\n\n3. Write a NumPy program to append values to the end of an array. For\ninstance: Original array: [10, 20, 30] . After that, append values to the end\nof the array: [10 20 30 40 50 60 70 80 90]\n\n4. Create two NumPy arrays and add the elements of both the arrays and\nstore the result in sumArray.\n\n5. Create a 3x3 array having values from 10-90 (interval of 10) and store that\nin array1\n\nPerform the following tasks:\na. Extract the 1st row from the array\nb. Extract the last element from the array\n  '

In [99]:
task_array = np.arange(2,11).reshape(3,3)

In [100]:
input_list = list(map(int,input().split()))

np.array(input_list).astype(float)

1 2 3 4 5 6 7 8 9 10


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [101]:
input_array = np.arange(10,20)
array_to_append = np.append(input_array,[40,50,60,70,80,90])
array_to_append

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 40, 50, 60, 70, 80, 90])

In [102]:
arr_test1 = np.arange(10,14).reshape(2,2)
arr_test2 = np.arange(1,5).reshape(2,2)
sumArray = arr_test1 + arr_test2

print(arr_test1)
print(arr_test2)
sumArray

[[10 11]
 [12 13]]
[[1 2]
 [3 4]]


array([[11, 13],
       [15, 17]])

In [103]:
array1= np.arange(10,91,10).reshape(3,3)
print(array1[0])
print(array1[2,2])


[10 20 30]
90


In [104]:
""" Problem Statement:
You work in XYZ Company as a Python developer. The company officials want
you to build a Python program.
Tasks To Be Performed:
1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return
[
[5, 5, 5],
[5, 5, 5],
[5, 5, 5]
]
2. Create a method that takes n NumPy arrays of the same dimensions,
sums them and returns the answer.
3. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]

top_left_sub_matrix (matrix, 2, 2) -> should return:

[
[1, 2]
[4, 5]
]


4. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
bottom-right N X M sub matrix, e.g:
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are
zero indexed)
[
[5, 6]
[8, 9]
]


5. Given a 1 D NumPy Array. Write a function that accepts this array as
parameters. The method should return a dictionary with 'mean' and
'std_dev' as key and array's mean and array's standard deviation as
values:
[1, 1, 1]
solution(arr) -> should return :
{'mean': 1.0, 'std_dev': 0.0}
"""

" Problem Statement:\nYou work in XYZ Company as a Python developer. The company officials want\nyou to build a Python program.\nTasks To Be Performed:\n1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric\nvalue and returns a NumPy array of the given dimension filled with the\ngiven value e.g.: solve((3, 3), 5) will return\n[\n[5, 5, 5],\n[5, 5, 5],\n[5, 5, 5]\n]\n2. Create a method that takes n NumPy arrays of the same dimensions,\nsums them and returns the answer.\n3. Given a 2 D Array of N X M Dimension, write a function that accepts this\narray as well as two numbers N and M. The method should return the\ntop-left N X M sub matrix, e.g:\n[\n[1, 2, 3],\n[4, 5, 6],\n[7, 8, 9],\n]\n\ntop_left_sub_matrix (matrix, 2, 2) -> should return:\n\n[\n[1, 2]\n[4, 5]\n]\n\n\n4. Given a 2 D Array of N X M Dimension, write a function that accepts this\narray as well as two numbers N and M. The method should return the\nbottom-right N X M sub matrix, e.g:\n[\n[1, 2, 3],\n

In [105]:
def function_problem_one(input_tuple,value):
  if len(input_tuple) == 2:
    return np.full(input_tuple,value)
  else:
    print("wrong dmensions")

input_tuple = tuple(map(int,input().split()))
value = int(input())
print(function_problem_one(input_tuple,value))

3 3
5
[[5 5 5]
 [5 5 5]
 [5 5 5]]


### **PANDAS**

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import pandas as pd

In [ ]:
series_num = pd.Series([1,2,3,4,5])
series_num

In [ ]:
series_text = pd.Series(["hello","hi","how"])
series_text


In [ ]:
# slicing

series_num[0]
series_num[0:3]


In [ ]:
series_text[0:2]

### **data frame**

In [ ]:
dataset_frames = pd.DataFrame({
    "stud_id": [1,2,3,4,5],
    "stud_num":[5,6,7,8,9],
    "student_n" :[5,6,7,8,9]
})

In [ ]:
dataset_frames

In [ ]:
market_data_frame = pd.read_csv("/content/market_fact.csv")
market_data_frame

In [ ]:
market_data_frame.head()    # first 4 rows of table

In [ ]:
market_data_frame.tail()  # first 4 rows of table

In [ ]:
market_data_frame.info()             # getting info about the table

In [ ]:
market_data_frame.isnull().sum()                     #which column have null values

In [ ]:
market_data_frame.columns

In [ ]:
market_data_frame.shape